binding:
  # bindings for all mode
  all:
    ctrl-q: ActionQuit					        # quit fff
  
  # bindings for normal mode
  normal:
    s:                                  # Prefix, Sort File
      "n": ActionSortByName               # Sort By Name
      m: ActionSortByMtime              # Sort By MTime
      s: ActionSortBySize               # Sort By Size
    .: ActionToggleHidden               # Toggle show hidden files
    d: ActionToggleDetail               # Toggle show file details
    j: ActionMoveDown                   # Move down
    k: ActionMoveUp                     # Move up
    l: ActionOpenFolderRight            # Open folder on right
    h: ActionCloseFolderRight           # Go to parent folder
    ",": ActionShift                    # Shift column
    <: ActionMoveToFirst                # Move to first item
    ">": ActionMoveToLast               # Move to last item
    ctrl-n: ActionMoveDown              # Move down
    ctrl-p: ActionMoveUp                # Move up
    enter: ActionOpenFolderRight        # Open folder on right
    b:                                  # Prefix, Bookmark manage
      b: ActionToggleBookmark           # Toggle show bookmark
      I: ActionJumpBookmark             # Jump over bookmarks
      i: ActionJumpBookmarkOnce         # Jump over bookmarks and stop after one jump
    g: ActionRefresh                    # Refresh current dir
    "1": ActionChangeGroup0             # Change group to 1
    "2": ActionChangeGroup1             # Change group to 2
    "3": ActionChangeGroup2             # Change group to 3
    "4": ActionChangeGroup3             # Change group to 4
    q: ActionQuit                       # quit fff
    up: ActionMoveUp                    # Move up
    down: ActionMoveDown                # Move down
    right: ActionOpenFolderRight        # Open folder on right
    left: ActionCloseFolderRight        # Go to parent folder
    m: ActionToggleMark                 # Toggle mark
    U: ActionClearMark                  # Clear all marks
    i: ActionJumpCurrentDirOnce         # Jump over current dir and stop after one jump
    I: ActionJumpCurrentDir             # Jump over current dir
    w: ActionJumpAllOnce                # Jump over items that can jump and stop after one jump
    W: ActionJumpAll                    # Jump over items that can jump

  # bindings for jump mode
  jump:
    enter: "ActionQuitJump"
    esc: "ActionQuitJump"

color:
  normal: default
  keyword: cyan
  folder: cyan
  file: default
  marked: yellow
  statusbar: cyan
  tab: cyan
  jump: yellow
  filter: blue
  indicator: green
