binding:
  # bindings for all mode
  all:
    "ctrl-q": ActionQuit					        # quit fff
  
  # bindings for normal mode
  normal:
    "s":                                  # Prefix, Sort File
      "n": ActionSortByName               # Sort By Name
      "m": ActionSortByMtime              # Sort By MTime
      "s": ActionSortBySize               # Sort By Size
    ".": ActionToggleHidden               # Toggle show hidden files
    "d": ActionToggleDetail               # Toggle show file details
    "j": ActionMoveDown                   # Move down
    "k": ActionMoveUp                     # Move up
    "l": ActionOpenFolderRight            # Open folder on right
    "h": ActionCloseFolderRight           # Go to parent folder
    "enter": ActionOpenFile               # Open file
    ",": ActionShift                      # Shift column
    "K": ActionMoveToFirst                # Move to first item
    "J": ActionMoveToLast                 # Move to last item
    "ctrl-n": ActionMoveDown              # Move down
    "ctrl-p": ActionMoveUp                # Move up
    "b":                                  # Prefix, Bookmark manage
      "b": ActionToggleBookmark           # Toggle show bookmark
      "n": ActionAddBookmark              # Bookmark current dir
      "d": ActionDeleteBookmark           # Delete bookmark
    "r": ActionRefresh                    # Refresh current dir
    "1": ActionChangeGroup0               # Change group to 1
    "2": ActionChangeGroup1               # Change group to 2
    "3": ActionChangeGroup2               # Change group to 3
    "4": ActionChangeGroup3               # Change group to 4
    "q": ActionQuit                       # quit fff
    "up": ActionMoveUp                    # Move up
    "down": ActionMoveDown                # Move down
    "right": ActionOpenFolderRight        # Open folder on right
    "left": ActionCloseFolderRight        # Go to parent folder
    "m": ActionToggleMark                 # Toggle mark
    "u": ActionClearMark                  # Clear all marks
    "g": ActionJumpCurrentDirOnce         # Jump over current dir and stop after one jump
    "G": ActionJumpCurrentDir             # Jump over current dir
    "i": ActionJumpAllOnce                # Jump over items that can jump and stop after one jump
    "I": ActionJumpAll                    # Jump over items that can jump
    "W": ActionJumpBookmark               # Jump over bookmarks
    "w": ActionJumpBookmarkOnce           # Jump over bookmarks and stop after one jump
    "f": ActionStartFilter                # Filter
    "F": ActionClearFilter                # Clear filter
    "+": ActionNewDir                     # Create new dir in current dir
    "N": ActionNewFile                    # Create new file in current dir
    "R": ActionRename                     # Rename current file
    "D": ActionDeleteFile                 # Delete marked files or current file
    "!": ActionShell                      # Run shell
    "e": ActionEdit                       # Run editor
    "v": ActionView                       # Run pager

  # bindings for jump mode
  jump:
    "enter": ActionQuitJump
    "esc": ActionQuitJump

  input:
    "enter": ActionQuitInputMode
    "esc": ActionAbortInputMode
    "backspace": ActionInputDelete

color:
  normal: default
  keyword: cyan
  folder: cyan
  file: default
  marked: yellow
  statusbar: cyan
  statusbar-title: magenta
  tab: cyan
  jump: yellow
  filter: magenta
  indicator: green

editor: vi
shell: sh
pager: less
